version: "3"

services:
  react-app:
    # stdin_open: true
    # tty: true
    build:
      context: .
      target: development
    ports: 
      - "3000:3000"
    volumes: 
      - ./src:/app/src
    env_file: 
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true

  server:
    build:
      context: .
      target: server
    expose: 
      - 4001
    ports:
      - "4001:4001"